const imgPath = '../../../assets/Images'

export const appLogo = require(`${imgPath}/appLogo.png`)
export const splashLogo = require(`${imgPath}/splash.png`)
export const CarouselBg = require(`${imgPath}/carouselBg.png`)
export const courseImg = require(`${imgPath}/courseImg.png`)

// export const forgotPassword = require(`${imgPath}/forgotpassword.png`)
// export const courseCompleted = require(`${imgPath}/coursecomp.png`)
// export const success = require(`${imgPath}/success.png`)

const iconsPath = '../../../assets/Icons'

export const backIcon = require(`${iconsPath}/back.png`)
export const ActiveBookmarks = require(`${iconsPath}/activeBookmark.png`)
export const ActiveCheck = require(`${iconsPath}/activeCheck.png`)
export const ActiveFav = require(`${iconsPath}/activefav.png`)
export const Bookmark = require(`${iconsPath}/bookmark.png`)
export const Call = require(`${iconsPath}/call.png`)
export const Camera = require(`${iconsPath}/camera.png`)
export const Check = require(`${iconsPath}/checkbox.png`)
export const Clock = require(`${iconsPath}/clock.png`)
export const Close = require(`${iconsPath}/close.png`)
export const CloseEye = require(`${iconsPath}/closeeye.png`)
export const Edit = require(`${iconsPath}/edit.png`)
export const Email = require(`${iconsPath}/email.png`)
export const Fav = require(`${iconsPath}/fav.png`)
export const Feed = require(`${iconsPath}/feed.png`)
export const FilterBg = require(`${iconsPath}/filterbg.png`)
export const Home = require(`${iconsPath}/home.png`)
export const Jobs = require(`${iconsPath}/jobs.png`)
export const MailBg = require(`${iconsPath}/mailbg.png`)
export const Mesg = require(`${iconsPath}/mesg.png`)
export const Notification = require(`${iconsPath}/notification.png`)
export const OpenEye = require(`${iconsPath}/openeye.png`)
export const Password = require(`${iconsPath}/password.png`)
export const Search = require(`${iconsPath}/search.png`)
export const SearchBg = require(`${iconsPath}/searchbg.png`)
export const Star = require(`${iconsPath}/star.png`)
export const UploadFile = require(`${iconsPath}/uploadFile.png`)
export const User = require(`${iconsPath}/user.png`)
export const Video = require(`${iconsPath}/video.png`)
export const Right = require(`${iconsPath}/right.png`)
export const seeAll = require(`${iconsPath}/seeAll.png`)
export const ProfileImg = require(`${iconsPath}/Profile.png`)
